NEKO_DATE_YEAR := $(shell date -u +%Y)
NEKO_DATE_MONTH := $(shell date -u +%m)
NEKO_DATE_DAY := $(shell date -u +%d)
NEKO_DATE_HOUR := $(shell date -u +%H)
NEKO_DATE_MINUTE := $(shell date -u +%M)
NEKO_BUILD_DATE_UTC := $(shell date -d '$(NEKO_DATE_YEAR)-$(NEKO_DATE_MONTH)-$(NEKO_DATE_DAY) $(NEKO_DATE_HOUR):$(NEKO_DATE_MINUTE) UTC' +%s)
NEKO_BUILD_DATE := $(NEKO_DATE_YEAR)$(NEKO_DATE_MONTH)$(NEKO_DATE_DAY)-$(NEKO_DATE_HOUR)$(NEKO_DATE_MINUTE)

NEKO_PLATFORM_VERSION := 14.0

NEKO_VERSION := neko_$(NEKO_BUILD)-$(NEKO_PLATFORM_VERSION)-$(NEKO_BUILD_DATE)
NEKO_VERSION_PROP := fourteen
